[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv:tests]
changedir = tests
deps =
    coverage[toml]

commands =
    coverage run -m unittest discover -p "*.py"
    coverage xml

[testenv:examples]
changedir = examples
allowlist_externals = /bin/bash

deps =
    jupyter
    jupyter_contrib_nbextensions
    matplotlib
    tqdm

commands =
    bash -c "for file in *.ipynb; do jupyter nbconvert --to notebook --output "../.tox/examples/$file" --execute "$file"; done"
"""

[tool.coverage.run]
branch = true
data_file = 'tests/.coverage'

[tool.coverage.report]
include = [
    "skcosmo/*"
]

[tool.coverage.xml]
output = 'tests/coverage.xml'
